name: CI

on:
  # allows us to run workflows manually
  workflow_dispatch:
  pull_request:
    branches:
      - develop
      - master
  push:
    branches:
      - develop
      - master

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


jobs:
  main:
    runs-on: ubuntu-18.04
    name: 'Trelis Svalinn Plugin 17.1 Build'


    steps:
      -
        uses: actions/checkout@v2

      -
        name: Environment Variables
        run: |
          echo "CURRENT=$(pwd)" >> $GITHUB_ENV
          echo "PLUGIN_ABS_PATH=" >> $GITHUB_ENV
          echo "SCRIPTPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV
          source $GITHUB_WORKSPACE/script/linux_share_build.sh

      -
        name: Apt dependencies
        shell: bash
        run: |
          sudo apt-get update -y
          sudo apt-get install -y g++ libtool libeigen3-dev libhdf5-dev patchelf git cmake

      -
        name: Build MOAB
        shell: bash
        run: |
          source $GITHUB_WORKSPACE/script/linux_share_build.sh
          build_moab

      -
        name: build DAGMC
        shell: bash
        run: build_dagmc

      -
        name: Trelis setup
        shell: bash
        run: setup_Trelis_sdk 17.1.0

      -
        name: build plugin
        shell: bash
        run: build_plugin 17.1.0

      -
        name: prepare pkg
        shell: bash
        run: build_plugin_pkg 17.1.0

  finish:
    needs: main
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true
